version: '3.4'

services:
  catalog_db:
    container_name: catalog_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog_db:27017"
    depends_on:
      - catalog_db
    ports:
      - "8000:80"
